
package ws.localdb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://webservice.localdb.lifecoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param personId
     * @return
     *     returns ws.localdb.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadPersonResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readPersonRequest", output = "http://webservice.localdb.lifecoach/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdatePersonResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/updatePersonRequest", output = "http://webservice.localdb.lifecoach/People/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.localdb.lifecoach/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeletePersonResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/deletePersonRequest", output = "http://webservice.localdb.lifecoach/People/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param measureId
     * @param personId
     * @param measureTypeId
     * @return
     *     returns ws.localdb.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadMeasure")
    @ResponseWrapper(localName = "readMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readMeasureRequest", output = "http://webservice.localdb.lifecoach/People/readMeasureResponse")
    public Measure readMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId,
        @WebParam(name = "measureId", targetNamespace = "")
        int measureId);

    /**
     * 
     * @return
     *     returns java.util.List<ws.localdb.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "getPeopleList", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetPeopleList")
    @ResponseWrapper(localName = "getPeopleListResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetPeopleListResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getPeopleListRequest", output = "http://webservice.localdb.lifecoach/People/getPeopleListResponse")
    public List<Person> getPeopleList();

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreatePersonResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/createPersonRequest", output = "http://webservice.localdb.lifecoach/People/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.localdb.lifecoach/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<ws.localdb.Measure>
     */
    @WebMethod
    @WebResult(name = "measureList", targetNamespace = "")
    @RequestWrapper(localName = "readLastMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadLastMeasure")
    @ResponseWrapper(localName = "readLastMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadLastMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readLastMeasureRequest", output = "http://webservice.localdb.lifecoach/People/readLastMeasureResponse")
    public List<Measure> readLastMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @param measureTypeId
     * @return
     *     returns ws.localdb.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readLastMeasureByType", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadLastMeasureByType")
    @ResponseWrapper(localName = "readLastMeasureByTypeResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadLastMeasureByTypeResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readLastMeasureByTypeRequest", output = "http://webservice.localdb.lifecoach/People/readLastMeasureByTypeResponse")
    public Measure readLastMeasureByType(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId);

    /**
     * 
     * @param personId
     * @param measureTypeId
     * @return
     *     returns java.util.List<ws.localdb.Measure>
     */
    @WebMethod
    @WebResult(name = "measureList", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureHistory", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetMeasureHistory")
    @ResponseWrapper(localName = "getMeasureHistoryResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetMeasureHistoryResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getMeasureHistoryRequest", output = "http://webservice.localdb.lifecoach/People/getMeasureHistoryResponse")
    public List<Measure> getMeasureHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId);

    /**
     * 
     * @param nMeasure
     * @param personId
     * @param measureTypeId
     * @return
     *     returns java.util.List<ws.localdb.Measure>
     */
    @WebMethod
    @WebResult(name = "measureList", targetNamespace = "")
    @RequestWrapper(localName = "getSomeMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetSomeMeasure")
    @ResponseWrapper(localName = "getSomeMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetSomeMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getSomeMeasureRequest", output = "http://webservice.localdb.lifecoach/People/getSomeMeasureResponse")
    public List<Measure> getSomeMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId,
        @WebParam(name = "nMeasure", targetNamespace = "")
        int nMeasure);

    /**
     * 
     * @param measure
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "measureId", targetNamespace = "")
    @RequestWrapper(localName = "createMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreateMeasure")
    @ResponseWrapper(localName = "createMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreateMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/createMeasureRequest", output = "http://webservice.localdb.lifecoach/People/createMeasureResponse")
    public int createMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measure", targetNamespace = "http://webservice.localdb.lifecoach/")
        Measure measure);

    /**
     * 
     * @param measure
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "measureId", targetNamespace = "")
    @RequestWrapper(localName = "updateMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdateMeasure")
    @ResponseWrapper(localName = "updateMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdateMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/updateMeasureRequest", output = "http://webservice.localdb.lifecoach/People/updateMeasureResponse")
    public int updateMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measure", targetNamespace = "http://webservice.localdb.lifecoach/")
        Measure measure);

    /**
     * 
     * @param measureId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteMeasure", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeleteMeasure")
    @ResponseWrapper(localName = "deleteMeasureResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeleteMeasureResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/deleteMeasureRequest", output = "http://webservice.localdb.lifecoach/People/deleteMeasureResponse")
    public int deleteMeasure(
        @WebParam(name = "measureId", targetNamespace = "")
        int measureId);

    /**
     * 
     * @param measureTypeId
     * @return
     *     returns ws.localdb.MeasureType
     */
    @WebMethod
    @WebResult(name = "measureType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureType", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadMeasureType")
    @ResponseWrapper(localName = "readMeasureTypeResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadMeasureTypeResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readMeasureTypeRequest", output = "http://webservice.localdb.lifecoach/People/readMeasureTypeResponse")
    public MeasureType readMeasureType(
        @WebParam(name = "measureTypeId", targetNamespace = "")
        int measureTypeId);

    /**
     * 
     * @param type
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idMeasureType", targetNamespace = "")
    @RequestWrapper(localName = "getIdMeasureTypeByType", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetIdMeasureTypeByType")
    @ResponseWrapper(localName = "getIdMeasureTypeByTypeResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetIdMeasureTypeByTypeResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getIdMeasureTypeByTypeRequest", output = "http://webservice.localdb.lifecoach/People/getIdMeasureTypeByTypeResponse")
    public int getIdMeasureTypeByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<ws.localdb.MeasureType>
     */
    @WebMethod
    @WebResult(name = "measureTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureTypeList", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetMeasureTypeList")
    @ResponseWrapper(localName = "getMeasureTypeListResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetMeasureTypeListResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getMeasureTypeListRequest", output = "http://webservice.localdb.lifecoach/People/getMeasureTypeListResponse")
    public List<MeasureType> getMeasureTypeList();

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<ws.localdb.Goal>
     */
    @WebMethod
    @WebResult(name = "goalList", targetNamespace = "")
    @RequestWrapper(localName = "getGoals", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoals")
    @ResponseWrapper(localName = "getGoalsResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalsResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getGoalsRequest", output = "http://webservice.localdb.lifecoach/People/getGoalsResponse")
    public List<Goal> getGoals(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param goalId
     * @param personId
     * @param measureTypeId
     * @return
     *     returns ws.localdb.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoal", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadGoal")
    @ResponseWrapper(localName = "readGoalResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadGoalResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readGoalRequest", output = "http://webservice.localdb.lifecoach/People/readGoalResponse")
    public Goal readGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId,
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

    /**
     * 
     * @param personId
     * @param measureTypeId
     * @return
     *     returns java.util.List<ws.localdb.Goal>
     */
    @WebMethod
    @WebResult(name = "goalList", targetNamespace = "")
    @RequestWrapper(localName = "getGoalHistory", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalHistory")
    @ResponseWrapper(localName = "getGoalHistoryResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalHistoryResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getGoalHistoryRequest", output = "http://webservice.localdb.lifecoach/People/getGoalHistoryResponse")
    public List<Goal> getGoalHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "measureTypeId", targetNamespace = "")
        String measureTypeId);

    /**
     * 
     * @param goal
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "goalId", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.CreateGoalResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/createGoalRequest", output = "http://webservice.localdb.lifecoach/People/createGoalResponse")
    public int createGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "goal", targetNamespace = "http://webservice.localdb.lifecoach/")
        Goal goal);

    /**
     * 
     * @param goal
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "goalId", targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.UpdateGoalResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/updateGoalRequest", output = "http://webservice.localdb.lifecoach/People/updateGoalResponse")
    public int updateGoal(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "goal", targetNamespace = "http://webservice.localdb.lifecoach/")
        Goal goal);

    /**
     * 
     * @param goalId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.DeleteGoalResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/deleteGoalRequest", output = "http://webservice.localdb.lifecoach/People/deleteGoalResponse")
    public int deleteGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

    /**
     * 
     * @param personId
     * @param title
     * @return
     *     returns ws.localdb.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "getGoalByTitle", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalByTitle")
    @ResponseWrapper(localName = "getGoalByTitleResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalByTitleResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getGoalByTitleRequest", output = "http://webservice.localdb.lifecoach/People/getGoalByTitleResponse")
    public Goal getGoalByTitle(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "title", targetNamespace = "")
        String title);

    /**
     * 
     * @param goalId
     * @return
     *     returns ws.localdb.GoalType
     */
    @WebMethod
    @WebResult(name = "goalType", targetNamespace = "")
    @RequestWrapper(localName = "readGoalType", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadGoalType")
    @ResponseWrapper(localName = "readGoalTypeResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.ReadGoalTypeResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/readGoalTypeRequest", output = "http://webservice.localdb.lifecoach/People/readGoalTypeResponse")
    public GoalType readGoalType(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

    /**
     * 
     * @return
     *     returns java.util.List<ws.localdb.GoalType>
     */
    @WebMethod
    @WebResult(name = "goalTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getGoalTypeList", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalTypeList")
    @ResponseWrapper(localName = "getGoalTypeListResponse", targetNamespace = "http://webservice.localdb.lifecoach/", className = "ws.localdb.GetGoalTypeListResponse")
    @Action(input = "http://webservice.localdb.lifecoach/People/getGoalTypeListRequest", output = "http://webservice.localdb.lifecoach/People/getGoalTypeListResponse")
    public List<GoalType> getGoalTypeList();

}
